export const products = [
  {
    slug: "amaranth-1kg",
    name: "Amaranth 1KG",
    category: "Pulses",
    price: "£2.99",
    image: "/products/AMARANTH 1KG.jpg",
    description: "High quality amaranth for wholesale and retail customers.",
  },
  {
    slug: "brown-chickpea-1kg",
    name: "Brown Chickpea 1KG",
    category: "Pulses",
    price: "£2.89",
    image: "/products/BROWN CHICKPEA 1KG.jpg",
    description: "Premium brown chickpeas, suitable for everyday cooking and bulk orders.",
  },
  {
    slug: "red-lentil-whole",
    name: "Red Lentil Whole",
    category: "Pulses",
    price: "£2.79",
    image: "/products/RED LENTIL WHOLE.jpg",
    description: "Premium whole red lentils with fast Manchester delivery and UK wide service.",
  },
  {
    slug: "black-eye-beans",
    name: "Black Eye Beans",
    category: "Pulses",
    price: "£2.99",
    image: "/products/BLACK EYE BEANS.jpg",
    description: "Quality black eye beans for wholesale and retail food customers.",
  },
  {
    slug: "basmati-rice-1kg",
    name: "Basmati Rice 1KG",
    category: "Rice",
    price: "£3.99",
    image: "/products/BASMATI RICE 1KG.jpg",
    description: "Fragrant basmati rice in a convenient 1KG pack.",
  },
  {
    slug: "bulgur-coarse",
    name: "Bulgur Coarse",
    category: "Pulses",
    price: "£2.49",
    image: "/products/BULGUR COARSE.jpg",
    description: "Coarse bulgur suitable for home cooking and shop supply.",
  },
  {
    slug: "couscous",
    name: "Couscous",
    category: "Pulses",
    price: "£2.49",
    image: "/products/COUCOUS.jpg",
    description: "Versatile couscous with great quality and fast delivery.",
  },
  {
    slug: "green-lentil-1kg",
    name: "Green Lentil 1KG",
    category: "Pulses",
    price: "£2.99",
    image: "/products/GREEN LENTIL 1KG.jpg",
    description: "Green lentils packed for both wholesale and retail customers.",
  },
  {
    slug: "jumbo-chickpea",
    name: "Jumbo Chickpea",
    category: "Pulses",
    price: "£3.49",
    image: "/products/JUMBO CHICKPEA.jpg",
    description: "Large premium chickpeas suitable for a wide range of dishes.",
  },
  {
    slug: "red-kidney-beans-1kg",
    name: "Red Kidney Beans 1KG",
    category: "Pulses",
    price: "£3.19",
    image: "/products/RED KIDNEY BEANS 1KG.jpg",
    description: "High quality red kidney beans with reliable UK service.",
  },
  {
    slug: "yellow-lentils-1kg",
    name: "Yellow Lentils 1KG",
    category: "Pulses",
    price: "£2.79",
    image: "/products/YELLOW LENTILS 1KG.jpg",
    description: "Yellow lentils for wholesale supply and everyday retail orders.",
  },
  {
    slug: "black-quinoa-1kg",
    name: "Black Quinoa 1KG",
    category: "Grains",
    price: "£4.99",
    image: "/products/BLACK QUINOA 1KG.jpg",
    description: "Premium black quinoa for health-focused customers and shops.",
  },
  {
    slug: "chia-seeds",
    name: "Chia Seeds",
    category: "Seeds",
    price: "£3.99",
    image: "/products/CHIA SEEDS.jpg",
    description: "Nutritious chia seeds ideal for both retail and bulk sales.",
  },
  {
    slug: "long-grain-rice-1kg",
    name: "Long Grain Rice 1KG",
    category: "Rice",
    price: "£2.99",
    image: "/products/LONG GRAIN RICE 1KG.jpg",
    description: "Everyday long grain rice in a clean 1KG retail pack.",
  },
  {
    slug: "pearl-barley-1kg",
    name: "Pearl Barley 1KG",
    category: "Grains",
    price: "£2.49",
    image: "/products/PEARL BARLEY 1KG.jpg",
    description: "Pearl barley for soups, salads, and everyday cooking.",
  },
  {
    slug: "sushi-rice-1kg",
    name: "Sushi Rice 1KG",
    category: "Rice",
    price: "£3.99",
    image: "/products/SUSHI RICE 1KG.jpg",
    description: "Quality sushi rice suitable for retail and food service use.",
  },
  {
    slug: "aytac-rice-1kg",
    name: "Aytac Rice 1KG",
    category: "Rice",
    price: "£2.99",
    image: "/products/AYTAC RICE 1KG.jpg",
    description: "Aytac rice in 1KG packaging for shops and direct customers.",
  },
  {
    slug: "black-sesame-seed",
    name: "Black Sesame Seed",
    category: "Seeds",
    price: "£3.49",
    image: "/products/BLACK SESAME SEED.jpg",
    description: "Premium black sesame seed with strong retail and wholesale appeal.",
  },
  {
    slug: "chickpea-1kg",
    name: "Chickpea 1KG",
    category: "Pulses",
    price: "£2.99",
    image: "/products/CHICKPEA 1KG.jpg",
    description: "Classic chickpea 1KG pack for everyday cooking.",
  },
  {
    slug: "dark-speckled-puy-lentils-1kg",
    name: "Dark Speckled Puy Lentils 1KG",
    category: "Pulses",
    price: "£3.99",
    image: "/products/DARK SPECKLED PUY LENTILS 1KG.jpg",
    description: "Premium lentils for customers looking for high-quality specialty products.",
  },
  {
    slug: "green-mung-beans-1kg",
    name: "Green Mung Beans 1KG",
    category: "Pulses",
    price: "£3.29",
    image: "/products/GREEN MUNG BEANS 1KG.jpg",
    description: "Quality mung beans suitable for home and wholesale customers.",
  },
  {
    slug: "pinto-beans-1kg",
    name: "Pinto Beans 1KG",
    category: "Pulses",
    price: "£3.19",
    image: "/products/PINTO BEANS 1KG.jpg",
    description: "Pinto beans in practical 1KG retail packaging.",
  },
  {
    slug: "red-lentil-split-masoor-dal-1kg",
    name: "Red Lentil Split (Masoor Dal) 1KG",
    category: "Pulses",
    price: "£2.79",
    image: "/products/RED LENTIL SPLIT (MASOOR DAL) 1KG.jpg",
    description: "Masoor dal in 1KG pack with reliable UK delivery.",
  },
  {
    slug: "roasted-buckwheat-1kg",
    name: "Roasted Buckwheat 1KG",
    category: "Grains",
    price: "£3.99",
    image: "/products/ROASTED BUCKWHEAT 1KG.jpg",
    description: "Roasted buckwheat for premium grain customers.",
  },
  {
    slug: "sesame-seed-hulled",
    name: "Sesame Seed Hulled",
    category: "Seeds",
    price: "£3.49",
    image: "/products/SESAME SEED HULLED.jpg",
    description: "Hulled sesame seed suitable for baking and cooking.",
  },
  {
    slug: "barley-flour",
    name: "Barley Flour",
    category: "Flour",
    price: "£2.49",
    image: "/products/BARLEY FLOUR.jpg",
    description: "Quality barley flour for retail and wholesale customers.",
  },
  {
    slug: "black-turtle-beans-1kg",
    name: "Black Turtle Beans 1KG",
    category: "Pulses",
    price: "£3.29",
    image: "/products/BLACK TURTLE BEANS 1KG.jpg",
    description: "Black turtle beans in a convenient 1KG pack.",
  },
  {
    slug: "brown-bulgur-coarse-1kg",
    name: "Brown Bulgur Coarse 1KG",
    category: "Pulses",
    price: "£2.49",
    image: "/products/BROWN BULGUR COARSE 1KG.jpg",
    description: "Brown coarse bulgur with dependable supply and delivery.",
  },
  {
    slug: "bulgur-coarse-1kg",
    name: "Bulgur Coarse 1KG",
    category: "Pulses",
    price: "£2.49",
    image: "/products/BULGUR COARSE 1KG.jpg",
    description: "Coarse bulgur suitable for retail packs and wholesale orders.",
  },
  {
    slug: "bulgur-medium-1kg",
    name: "Bulgur Medium 1KG",
    category: "Pulses",
    price: "£2.49",
    image: "/products/BULGUR MEDIUM 1KG.jpg",
    description: "Medium bulgur for households, shops and restaurants.",
  },
  {
    slug: "corn-flour",
    name: "Corn Flour",
    category: "Flour",
    price: "£1.99",
    image: "/products/CORN FLOUR.jpg",
    description: "Corn flour for everyday kitchen and trade use.",
  },
  {
    slug: "easy-cook-rice-1kg",
    name: "Easy Cook Rice 1KG",
    category: "Rice",
    price: "£2.99",
    image: "/products/EASY COOK RICE 1KG.jpg",
    description: "Easy cook rice in a simple 1KG pack.",
  },
  {
    slug: "green-peas-1kg",
    name: "Green Peas 1KG",
    category: "Pulses",
    price: "£2.59",
    image: "/products/GREEN PEAS 1KG.jpg",
    description: "Green peas for fast retail sales and local shop supply.",
  },
  {
    slug: "marrowfat-green-peas-1kg",
    name: "Marrowfat Green Peas 1KG",
    category: "Pulses",
    price: "£2.79",
    image: "/products/MARROWFAT GREEN PEAS 1KG.jpg",
    description: "Marrowfat green peas suitable for traditional dishes.",
  },
  {
    slug: "popcorn",
    name: "Popcorn",
    category: "Snacks",
    price: "£2.49",
    image: "/products/POPCORN.jpg",
    description: "Popcorn kernels for home and retail customers.",
  },
  {
    slug: "sella-basmati-rice-1kg",
    name: "Sella Basmati Rice 1KG",
    category: "Rice",
    price: "£4.49",
    image: "/products/SELLA BASMATI RICE 1KG.jpg",
    description: "High quality sella basmati rice for trade and home cooking.",
  },
  {
    slug: "sesame-seed-natural",
    name: "Sesame Seed Natural",
    category: "Seeds",
    price: "£3.49",
    image: "/products/SESAME SEED NATURAL.jpg",
    description: "Natural sesame seed in retail-friendly packaging.",
  },
  {
    slug: "thai-jasmin-rice-1kg",
    name: "Thai Jasmin Rice 1KG",
    category: "Rice",
    price: "£4.29",
    image: "/products/THAI JASMIN RICE 1KG.jpg",
    description: "Fragrant Thai jasmine rice in 1KG pack.",
  },
  {
    slug: "white-beans",
    name: "White Beans",
    category: "Pulses",
    price: "£2.99",
    image: "/products/WHITE BEANS.jpg",
    description: "Classic white beans with dependable UK delivery.",
  },
  {
    slug: "black-beluga-lentils-1kg",
    name: "Black Beluga Lentils 1KG",
    category: "Pulses",
    price: "£4.99",
    image: "/products/BLACK BELUGA LENTILS 1KG.jpg",
    description: "Premium black beluga lentils for specialty and health-focused customers.",
  },
  {
    slug: "borlotti-rosecoco-beans-1kg",
    name: "Borlotti Rosecoco Beans 1KG",
    category: "Pulses",
    price: "£3.49",
    image: "/products/BORLOTTI ROSECOCO BEANS 1KG.jpg",
    description: "Premium borlotti rosecoco beans packed for retail and wholesale sale.",
  },
  {
    slug: "brown-bulgur-fine-1kg",
    name: "Brown Bulgur Fine 1KG",
    category: "Pulses",
    price: "£2.49",
    image: "/products/BROWN BULGUR FINE 1KG.jpg",
    description: "Fine brown bulgur with everyday retail appeal.",
  },
  {
    slug: "bulgur-coarse-with-vermicelli-1kg",
    name: "Bulgur Coarse with Vermicelli 1KG",
    category: "Pulses",
    price: "£2.79",
    image: "/products/BULGUR COARSE WITH VERMICELLI 1KG.jpg",
    description: "Coarse bulgur with vermicelli in a convenient 1KG pack.",
  },
  {
    slug: "bulgur-medium-with-vermicelli-1kg",
    name: "Bulgur Medium with Vermicelli 1KG",
    category: "Pulses",
    price: "£2.79",
    image: "/products/BULGUR MEDIUM WITH VERMICELLI 1KG.jpg",
    description: "Medium bulgur with vermicelli suitable for shops and direct customers.",
  },
  {
    slug: "corn-meal-extra-coarse-1kg",
    name: "Corn Meal Extra Coarse 1KG",
    category: "Flour",
    price: "£2.19",
    image: "/products/CORN MEAL EXTRA COARSE 1KG.jpg",
    description: "Extra coarse corn meal for a variety of traditional uses.",
  },
  {
    slug: "flax-seeds",
    name: "Flax Seeds",
    category: "Seeds",
    price: "£2.99",
    image: "/products/FLAX SEEDS.jpg",
    description: "Flax seeds for healthy retail products and wholesale supply.",
  },
  {
    slug: "green-peas-split-1kg",
    name: "Green Peas Split 1KG",
    category: "Pulses",
    price: "£2.59",
    image: "/products/GREEN PEAS SPLIT 1KG.jpg",
    description: "Split green peas in a 1KG pack.",
  },
  {
    slug: "mix-quinoa-1kg",
    name: "Mix Quinoa 1KG",
    category: "Grains",
    price: "£5.49",
    image: "/products/MIX QUINOA 1KG.jpg",
    description: "Mixed quinoa for premium grocery customers.",
  },
  {
    slug: "pudding-rice-1kg",
    name: "Pudding Rice 1KG",
    category: "Rice",
    price: "£2.99",
    image: "/products/PUDDING RICE 1KG.jpg",
    description: "Pudding rice ideal for sweet dishes and desserts.",
  },
  {
    slug: "small-white-beans-1kg",
    name: "Small White Beans 1KG",
    category: "Pulses",
    price: "£2.99",
    image: "/products/SMALL WHITE BEANS 1KG.jpg",
    description: "Small white beans with dependable retail packaging.",
  },
  {
    slug: "toor-dal-1kg",
    name: "Toor Dal 1KG",
    category: "Pulses",
    price: "£3.49",
    image: "/products/TOOR DAL 1KG.jpg",
    description: "Toor dal 1KG pack for wholesale and retail customers.",
  },
];